import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { describe, expect, it } from 'vitest'

// tests/routes.json is the web layer's route inventory: the list the staging and
// cutover checks walk to prove every endpoint still answers. It is generated by
// tests/routes.json.sh; this test keeps it from drifting from server/api.

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n)
    return statSync(p).isDirectory() ? walk(p) : [p]
  })
}

function fromFiles(): string[] {
  const root = join(__dirname, '..', 'server', 'api')
  return walk(root)
    .filter((f) => f.endsWith('.ts'))
    .map((f) => {
      const rel = relative(root, f)
      const m = rel.match(/\.(get|post|put|patch|delete)\.ts$/)!
      const path = rel
        .replace(/\.(get|post|put|patch|delete)\.ts$/, '')
        .replace(/\/index$/, '')
        .replace(/\[([^\]]+)\]/g, ':$1')
      return `${m[1].toUpperCase()} /api/${path}`
    })
    .sort()
}

describe('route inventory', () => {
  it('matches server/api', () => {
    const listed = (JSON.parse(readFileSync(join(__dirname, 'routes.json'), 'utf8')) as { method: string; path: string }[])
      .map((r) => `${r.method} ${r.path}`)
      .sort()
    expect(listed).toEqual(fromFiles())
  })
})
